basic_settings:
  site_title: Angel Colberg
  site_tagline: Design Use Cases
  favicon_image: /images/favicon.png

header_settings:
  logo_image: /images/logo.png
  logo_width: 40

menu_settings:
  menu_items:
    - title: 'Use Cases'
      url: '/'
    - title: 'About'
      url: '/about'

grid_settings:
  overlay_opacity: 1.0
  grid_spacing: 20

social_settings:
  facebook_url: 'https://www.facebook.com/angelcolbergdesign'
  twitter_url: ''
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: 'https://dribbble.com/angelcolberg'
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: 'https://www.flickr.com/photos/killerpanda/'
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: 'https://www.linkedin.com/in/angelcolberg/'

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#F5F7FA'
  text_dark_color: '#2A2F36'
  text_medium_color: '#6C7A89'
  text_light_color: '#ABB7B7'
  accent_color: '#E91E63'
  border_color: '#eeeeee'
  overlay_background_color: '#E91E63'
  overlay_text_color: '#fff'
  overlay_accent_color: '#2A2F36'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Roboto+Condensed|Nanum+Gothic+Coding" rel="stylesheet">'
  title_font: '"Nanum Gothic Coding", sans-serif'
  body_font: '"Roboto Condensed", sans-serif'
  menu_font: '"Roboto Condensed", sans-serif'
  mono_font: '"Nanum Gothic Coding", sans-serif'
  display_font: '"Nanum Gothic Coding", sans-serif'
  regular_weight: 300
  bold_weight: 500
  site_title:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 500
    letter_spacing: 0
  site_tagline:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 300
    letter_spacing: 0
    line_height: 1.5
  menu:
    small_size: 30
    medium_size: 15
    large_size: 16
    weight: 500
    letter_spacing: 0
  grid_item_title:
    small_size: 22
    medium_size: 26
    large_size: 30
    weight: 100
    letter_spacing: 0
  grid_item_subtitle:
    small_size: 15
    medium_size: 16
    large_size: 17
    weight: 300
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 100
    letter_spacing: 0
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 300
    letter_spacing: 0
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 300
    letter_spacing: 0
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 200
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 100
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: 0
    line_height: 1.6
  buttons:
    weight: 500
    letter_spacing: 0

advanced_settings:
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""